version: "3.8"
services:
    php:
        build:
            args:
                user: teladoc
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: travellist
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
        - ./:/var/www
    
    database:
        image: backoffice-db
        ports:
            - "3306:3036"
        environment:
            MYSQL_ROOT_PASSWORD: RootPassword
            MYSQL_DATABASE: Backoffice
            MYSQL_USER: MainUser
            MYSQL_PASSWORD: MainPassword
        volumes:
        - db-volume:/var/lib/mysql
volumes:
    data:
