version: "3.8"
services:
    php:
        build:
            args:
                user: teladoc
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: travellist
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
        - ./:/var/www
volumes:
    data:
